# AWSTATS DOMAINS DATABASE
#-------------------------------------------------------
# If you want to add a new domain to extend AWStats database detection capabilities,
# you must add an entry in DomainsHashIDLib.
#-------------------------------------------------------
# Based on IANA Root Zone Database (https://www.iana.org/domains/root/db)
# Last updated: 2026-03-31
#-------------------------------------------------------
# DomainsHashIDLib
# 域名后缀 -> 显示名称 映射表
# 包含:
#   - 国家及地区代码顶级域 (ccTLD), 如 .cn, .us, .uk
#   - 通用顶级域 (gTLD), 如 .com, .org, .net
#   - 新通用顶级域 (new gTLD), 如 .app, .blog, .shop
#   - 国际化域名 (IDN), 如 .中国, .рф, .香港
#   - 特殊用途域名, 如 localhost, arpa
#-------------------------------------------------------
%DomainsHashIDLib = (
# Special/Internal
'localhost','localhost',
'i0','Satellite access host',
'a1','Satellite access host',
'a2','Satellite access host',
'ap','Asia/Pacific Region',

# Country Code Top-Level Domains (ccTLD)
'ac','Ascension Island',
'ad','Andorra',
'ae','United Arab Emirates',
'af','Afghanistan',
'ag','Antigua and Barbuda',
'ai','Anguilla',
'al','Albania',
'am','Armenia',
'an','Netherlands Antilles (Not assigned)',
'ao','Angola',
'aq','Antarctica',
'ar','Argentina',
'as','American Samoa',
'at','Austria',
'au','Australia',
'aw','Aruba',
'ax','Aland Islands',
'az','Azerbaijan',
'ba','Bosnia and Herzegovina',
'bb','Barbados',
'bd','Bangladesh',
'be','Belgium',
'bf','Burkina Faso',
'bg','Bulgaria',
'bh','Bahrain',
'bi','Burundi',
'bj','Benin',
'bl','Saint Barthelemy (Not assigned)',
'bm','Bermuda',
'bn','Brunei Darussalam',
'bo','Bolivia',
'bq','Bonaire, Sint Eustatius and Saba (Not assigned)',
'br','Brazil',
'bs','Bahamas',
'bt','Bhutan',
'bv','Bouvet Island',
'bw','Botswana',
'by','Belarus',
'bz','Belize',
'ca','Canada',
'cc','Cocos (Keeling) Islands',
'cd','Congo, Democratic Republic of the',
'cf','Central African Republic',
'cg','Congo',
'ch','Switzerland',
'ci','Cote d\'Ivoire',
'ck','Cook Islands',
'cl','Chile',
'cm','Cameroon',
'cn','China',
'co','Colombia',
'cr','Costa Rica',
'cu','Cuba',
'cv','Cape Verde',
'cw','Curacao',
'cx','Christmas Island',
'cy','Cyprus',
'cz','Czech Republic',
'de','Germany',
'dj','Djibouti',
'dk','Denmark',
'dm','Dominica',
'do','Dominican Republic',
'dz','Algeria',
'ec','Ecuador',
'ee','Estonia',
'eg','Egypt',
'er','Eritrea',
'es','Spain',
'et','Ethiopia',
'eu','European Union',
'fi','Finland',
'fj','Fiji',
'fk','Falkland Islands',
'fm','Micronesia',
'fo','Faroe Islands',
'fr','France',
'ga','Gabon',
'gb','United Kingdom',
'gd','Grenada',
'ge','Georgia',
'gf','French Guiana',
'gg','Guernsey',
'gh','Ghana',
'gi','Gibraltar',
'gl','Greenland',
'gm','Gambia',
'gn','Guinea',
'gp','Guadeloupe',
'gq','Equatorial Guinea',
'gr','Greece',
'gs','South Georgia and South Sandwich Islands',
'gt','Guatemala',
'gu','Guam',
'gw','Guinea-Bissau',
'gy','Guyana',
'hk','Hong Kong',
'hm','Heard and McDonald Islands',
'hn','Honduras',
'hr','Croatia',
'ht','Haiti',
'hu','Hungary',
'id','Indonesia',
'ie','Ireland',
'il','Israel',
'im','Isle of Man',
'in','India',
'io','British Indian Ocean Territory',
'iq','Iraq',
'ir','Iran',
'is','Iceland',
'it','Italy',
'je','Jersey',
'jm','Jamaica',
'jo','Jordan',
'jp','Japan',
'ke','Kenya',
'kg','Kyrgyzstan',
'kh','Cambodia',
'ki','Kiribati',
'km','Comoros',
'kn','Saint Kitts and Nevis',
'kp','Korea, Democratic People\'s Republic of',
'kr','Korea, Republic of',
'kw','Kuwait',
'ky','Cayman Islands',
'kz','Kazakhstan',
'la','Laos',
'lb','Lebanon',
'lc','Saint Lucia',
'li','Liechtenstein',
'lk','Sri Lanka',
'lr','Liberia',
'ls','Lesotho',
'lt','Lithuania',
'lu','Luxembourg',
'lv','Latvia',
'ly','Libya',
'ma','Morocco',
'mc','Monaco',
'md','Moldova',
'me','Montenegro',
'mf','Saint Martin (French)',
'mg','Madagascar',
'mh','Marshall Islands',
'mk','North Macedonia',
'ml','Mali',
'mm','Myanmar',
'mn','Mongolia',
'mo','Macau',
'mp','Northern Mariana Islands',
'mq','Martinique',
'mr','Mauritania',
'ms','Montserrat',
'mt','Malta',
'mu','Mauritius',
'mv','Maldives',
'mw','Malawi',
'mx','Mexico',
'my','Malaysia',
'mz','Mozambique',
'na','Namibia',
'nc','New Caledonia',
'ne','Niger',
'nf','Norfolk Island',
'ng','Nigeria',
'ni','Nicaragua',
'nl','Netherlands',
'no','Norway',
'np','Nepal',
'nr','Nauru',
'nu','Niue',
'nz','New Zealand',
'om','Oman',
'pa','Panama',
'pe','Peru',
'pf','French Polynesia',
'pg','Papua New Guinea',
'ph','Philippines',
'pk','Pakistan',
'pl','Poland',
'pm','Saint Pierre and Miquelon',
'pn','Pitcairn',
'pr','Puerto Rico',
'ps','Palestine',
'pt','Portugal',
'pw','Palau',
'py','Paraguay',
'qa','Qatar',
're','Reunion',
'ro','Romania',
'rs','Serbia',
'ru','Russian Federation',
'rw','Rwanda',
'sa','Saudi Arabia',
'sb','Solomon Islands',
'sc','Seychelles',
'sd','Sudan',
'se','Sweden',
'sg','Singapore',
'sh','Saint Helena',
'si','Slovenia',
'sj','Svalbard and Jan Mayen',
'sk','Slovakia',
'sl','Sierra Leone',
'sm','San Marino',
'sn','Senegal',
'so','Somalia',
'sr','Suriname',
'ss','South Sudan',
'st','Sao Tome and Principe',
'su','Soviet Union (former)',
'sv','El Salvador',
'sx','Sint Maarten',
'sy','Syria',
'sz','Eswatini',
'tc','Turks and Caicos Islands',
'td','Chad',
'tf','French Southern Territories',
'tg','Togo',
'th','Thailand',
'tj','Tajikistan',
'tk','Tokelau',
'tl','Timor-Leste',
'tm','Turkmenistan',
'tn','Tunisia',
'to','Tonga',
'tr','Turkey',
'tt','Trinidad and Tobago',
'tv','Tuvalu',
'tw','Taiwan',
'tz','Tanzania',
'ua','Ukraine',
'ug','Uganda',
'uk','United Kingdom',
'um','United States Minor Outlying Islands',
'us','United States',
'uy','Uruguay',
'uz','Uzbekistan',
'va','Vatican City',
'vc','Saint Vincent and the Grenadines',
've','Venezuela',
'vg','Virgin Islands (British)',
'vi','Virgin Islands (U.S.)',
'vn','Vietnam',
'vu','Vanuatu',
'wf','Wallis and Futuna',
'ws','Samoa',
'ye','Yemen',
'yt','Mayotte',
'za','South Africa',
'zm','Zambia',
'zw','Zimbabwe',

# Generic Top-Level Domains (gTLD)
'aero','Aero/Travel domains',
'biz','Biz domains',
'cat','Catalan',
'com','Commercial',
'coop','Coop domains',
'edu','USA Educational',
'gov','USA Government',
'info','Info domains',
'int','International',
'jobs','Jobs domains',
'mil','USA Military',
'mobi','Mobi domains',
'museum','Museum domains',
'name','Name domains',
'net','Network',
'org','Non-Profit Organizations',
'pro','Professional domains',
'tel','Tel domains',
'travel','Travel domains',
'xxx','Adult domains',

# New gTLDs (selected)
'aaa','American Automobile Association',
'aarp','AARP',
'abb','ABB Ltd',
'abbott','Abbott Laboratories',
'abbvie','AbbVie Inc',
'abc','Disney Enterprises',
'able','Able Inc',
'abogado','Registry Services',
'abudhabi','Abu Dhabi Systems and Information Centre',
'academy','Binky Moon',
'accenture','Accenture plc',
'accountant','dot Accountant Limited',
'accountants','Binky Moon',
'aco','ACO Severin Ahlmann',
'actor','Dog Beach',
'adac','ADAC',
'ads','Charleston Road Registry',
'adult','ICM Registry AD',
'aeg','Aktiebolaget Electrolux',
'aetna','Aetna Life Insurance Company',
'afamilycompany','Not assigned',
'afl','Australian Football League',
'africa','ZA Central Registry',
'agakhan','Fondation Aga Khan',
'agency','Binky Moon',
'aig','American International Group',
'airbus','Airbus S.A.S.',
'airforce','Dog Beach',
'airtel','Bharti Airtel',
'akdn','Fondation Aga Khan',
'alfaromeo','Not assigned',
'alibaba','Alibaba Group',
'alipay','Alibaba Group',
'allfinanz','Allfinanz Deutsche Vermögensberatung',
'allstate','Allstate Fire and Casualty',
'ally','Ally Financial',
'alsace','REGION GRAND EST',
'alstom','ALSTOM',
'amazon','Amazon Registry Services',
'americanexpress','American Express',
'americanfamily','AmFam',
'amex','American Express',
'amfam','AmFam',
'amica','Amica Mutual Insurance',
'amsterdam','Gemeente Amsterdam',
'analytics','Campus IP',
'android','Charleston Road Registry',
'anquan','Beijing Qihu Keji',
'anz','Australia and New Zealand Banking Group',
'aol','Yahoo Inc.',
'apartments','Binky Moon',
'app','Charleston Road Registry',
'apple','Apple Inc.',
'aquarelle','Aquarelle.com',
'arab','League of Arab States',
'aramco','Aramco Services Company',
'archi','Identity Digital',
'army','Dog Beach',
'art','UK Creative Ideas',
'arte','Association Relative à la Télévision Européenne',
'asda','Asda Stores',
'asia','DotAsia Organisation',
'associates','Binky Moon',
'athleta','The Gap',
'attorney','Dog Beach',
'auction','Dog Beach',
'audi','AUDI Aktiengesellschaft',
'audible','Amazon Registry Services',
'audio','XYZ.COM',
'auspost','Australian Postal Corporation',
'author','Amazon Registry Services',
'auto','XYZ.COM',
'autos','XYZ.COM',
'avianca','Not assigned',
'aws','AWS Registry',
'axa','AXA Group Operations',
'azure','Microsoft Corporation',
'baby','XYZ.COM',
'baidu','Baidu',
'banamex','Citigroup',
'bananarepublic','Not assigned',
'band','Dog Beach',
'bank','fTLD Registry Services',
'bar','Punto 2012',
'barcelona','Municipi de Barcelona',
'barclaycard','Barclays Bank',
'barclays','Barclays Bank',
'barefoot','Gallo Vineyards',
'bargains','Binky Moon',
'baseball','MLB Advanced Media',
'basketball','Fédération Internationale de Basketball',
'bauhaus','Werkhaus',
'bayern','Bayern Connect',
'bbc','British Broadcasting Corporation',
'bbt','BB&T Corporation',
'bbva','Banco Bilbao Vizcaya Argentaria',
'bcg','The Boston Consulting Group',
'bcn','Municipi de Barcelona',
'beats','Beats Electronics',
'beauty','XYZ.COM',
'beer','Registry Services',
'bentley','Bentley Motors',
'berlin','dotBERLIN',
'best','BestTLD',
'bestbuy','BBY Solutions',
'bet','Identity Digital',
'bharti','Bharti Enterprises',
'bible','American Bible Society',
'bid','dot Bid Limited',
'bike','Binky Moon',
'bing','Microsoft Corporation',
'bingo','Binky Moon',
'bio','Identity Digital',
'black','Identity Digital',
'blackfriday','Registry Services',
'blanco','Not assigned',
'blockbuster','Dish DBS',
'blog','Knock Knock WHOIS There',
'bloomberg','Bloomberg IP Holdings',
'blue','Identity Digital',
'bms','Bristol-Myers Squibb',
'bmw','Bayerische Motoren Werke',
'bnl','Not assigned',
'bnpparibas','BNP Paribas',
'boats','XYZ.COM',
'boehringer','Boehringer Ingelheim',
'bofa','Bank of America',
'bom','NIC.br',
'bond','Shortdot SA',
'boo','Charleston Road Registry',
'book','Amazon Registry Services',
'booking','Booking.com',
'boots','Not assigned',
'bosch','Robert Bosch',
'bostik','Bostik SA',
'boston','Registry Services',
'bot','Amazon Registry Services',
'boutique','Binky Moon',
'box','Intercap Registry',
'bradesco','Banco Bradesco',
'bridgestone','Bridgestone Corporation',
'broadway','Celebrate Broadway',
'broker','Dog Beach',
'brother','Brother Industries',
'brussels','DNS.be',
'budapest','Not assigned',
'bugatti','Not assigned',
'build','Plan Bee',
'builders','Binky Moon',
'business','Binky Moon',
'buy','Amazon Registry Services',
'buzz','DOTSTRATEGY',
'bzh','Association www.bzh',
'cab','Binky Moon',
'cafe','Binky Moon',
'cal','Charleston Road Registry',
'call','Amazon Registry Services',
'calvinklein','PVH gTLD Holdings',
'cam','CAM Connecting',
'camera','Binky Moon',
'camp','Binky Moon',
'cancerresearch','Not assigned',
'canon','Canon',
'capetown','ZA Central Registry',
'capital','Binky Moon',
'capitalone','Capital One',
'car','XYZ.COM',
'caravan','Caravan International',
'cards','Binky Moon',
'care','Binky Moon',
'career','dotCareer',
'careers','Binky Moon',
'cars','XYZ.COM',
'cartier','Cartier',
'casa','Registry Services',
'case','Digity',
'caseih','Not assigned',
'cash','Binky Moon',
'casino','Binky Moon',
'catering','Binky Moon',
'catholic','Pontifical Council for Social Communication',
'cba','Commonwealth Bank of Australia',
'cbn','Christian Broadcasting Network',
'cbre','CBRE',
'cbs','Not assigned',
'ceb','Not assigned',
'center','Binky Moon',
'ceo','XYZ.COM',
'cern','CERN',
'cfa','CFA Institute',
'cfd','Shortdot SA',
'chanel','Chanel International',
'channel','Charleston Road Registry',
'charity','Public Interest Registry',
'chase','JPMorgan Chase',
'chat','Binky Moon',
'cheap','Binky Moon',
'chintai','CHINTAI Corporation',
'chloe','Not assigned',
'christmas','XYZ.COM',
'chrome','Charleston Road Registry',
'chrysler','Not assigned',
'church','Binky Moon',
'cipriani','Hotel Cipriani',
'circle','Amazon Registry Services',
'cisco','Cisco Technology',
'citadel','Citadel Domain',
'citi','Citigroup',
'citic','CITIC Group',
'city','Binky Moon',
'cityeats','Not assigned',
'claims','Binky Moon',
'cleaning','Binky Moon',
'click','Internet Naming',
'clinic','Binky Moon',
'clinique','The Estée Lauder Companies',
'clothing','Binky Moon',
'cloud','ARUBA PEC',
'club','Registry Services',
'clubmed','Club Méditerranée',
'coach','Binky Moon',
'codes','Binky Moon',
'coffee','Binky Moon',
'college','XYZ.COM',
'cologne','dotKoeln',
'comcast','Not assigned',
'commbank','Commonwealth Bank of Australia',
'community','Binky Moon',
'company','Binky Moon',
'compare','Registry Services',
'computer','Binky Moon',
'comsec','VeriSign',
'condos','Binky Moon',
'construction','Binky Moon',
'consulting','Dog Beach',
'contact','Dog Beach',
'contractors','Binky Moon',
'cooking','Registry Services',
'cookingchannel','Not assigned',
'cool','Binky Moon',
'corsica','Collectivité de Corse',
'country','Internet Naming',
'coupon','Amazon Registry Services',
'coupons','Binky Moon',
'courses','Registry Services',
'cpa','American Institute of CPAs',
'credit','Binky Moon',
'creditcard','Binky Moon',
'creditunion','DotCooperation',
'cricket','dot Cricket',
'crown','Crown Equipment',
'crs','Federated Co-operatives',
'cruise','Viking River Cruises',
'cruises','Binky Moon',
'csc','Not assigned',
'cuisinella','SCHMIDT GROUPE',
'cymru','Nominet UK',
'cyou','Shortdot SA',
'dabur','Not assigned',
'dad','Charleston Road Registry',
'dance','Dog Beach',
'data','Dish DBS',
'date','dot Date',
'dating','Binky Moon',
'datsun','Nissan Motor',
'day','Charleston Road Registry',
'dclk','Charleston Road Registry',
'dds','Registry Services',
'deal','Amazon Registry Services',
'dealer','Intercap Registry',
'deals','Binky Moon',
'degree','Dog Beach',
'delivery','Binky Moon',
'dell','Dell',
'deloitte','Deloitte Touche Tohmatsu',
'delta','Delta Air Lines',
'democrat','Dog Beach',
'dental','Binky Moon',
'dentist','Dog Beach',
'desi','Emergency Back-End Registry Operator',
'design','Registry Services',
'dev','Charleston Road Registry',
'dhl','Deutsche Post',
'diamonds','Binky Moon',
'diet','XYZ.COM',
'digital','Binky Moon',
'direct','Binky Moon',
'directory','Binky Moon',
'discount','Binky Moon',
'discover','Discover Financial',
'dish','Dish DBS',
'diy','Internet Naming',
'dnp','Dai Nippon Printing',
'docs','Charleston Road Registry',
'doctor','Binky Moon',
'dodge','Not assigned',
'dog','Binky Moon',
'doha','Not assigned',
'domains','Binky Moon',
'doosan','Not assigned',
'dot','Dish DBS',
'download','dot Support',
'drive','Charleston Road Registry',
'dtv','Dish DBS',
'dubai','Dubai Smart Government',
'duck','Not assigned',
'dunlop','Not assigned',
'duns','Not assigned',
'dupont','DuPont',
'durban','ZA Central Registry',
'dvag','Deutsche Vermögensberatung',
'dvr','DISH Technologies',
'earth','Interlink Systems Innovation',
'eat','Charleston Road Registry',
'eco','Big Room',
'edeka','EDEKA',
'education','Binky Moon',
'email','Binky Moon',
'emerck','Merck KGaA',
'emerson','Not assigned',
'energy','Binky Moon',
'engineer','Dog Beach',
'engineering','Binky Moon',
'enterprises','Binky Moon',
'epost','Not assigned',
'epson','Seiko Epson',
'equipment','Binky Moon',
'ericsson','Telefonaktiebolaget LM Ericsson',
'erni','ERNI Group',
'esq','Charleston Road Registry',
'estate','Binky Moon',
'esurance','Not assigned',
'etisalat','Not assigned',
'eurovision','European Broadcasting Union',
'eus','Puntueus Fundazioa',
'events','Binky Moon',
'everbank','Not assigned',
'exchange','Binky Moon',
'expert','Binky Moon',
'exposed','Binky Moon',
'express','Binky Moon',
'extraspace','Extra Space Storage',
'fage','Fage International',
'fail','Binky Moon',
'fairwinds','FairWinds Partners',
'faith','dot Faith',
'family','Dog Beach',
'fan','Dog Beach',
'fans','ZDNS International',
'farm','Binky Moon',
'farmers','Farmers Insurance',
'fashion','Registry Services',
'fast','Amazon Registry Services',
'fedex','Federal Express',
'feedback','Top Level Spectrum',
'ferrari','Fiat Chrysler Automobiles',
'ferrero','Ferrero Trading',
'fiat','Not assigned',
'fidelity','Fidelity Brokerage Services',
'fido','Rogers Communications',
'film','Motion Picture Domain Registry',
'final','NIC.br',
'finance','Binky Moon',
'financial','Binky Moon',
'fire','Amazon Registry Services',
'firestone','Bridgestone',
'firmdale','Firmdale Holdings',
'fish','Binky Moon',
'fishing','Registry Services',
'fit','Registry Services',
'fitness','Binky Moon',
'flickr','Flickr',
'flights','Binky Moon',
'flir','FLIR Systems',
'florist','Binky Moon',
'flowers','XYZ.COM',
'flsmidth','Not assigned',
'fly','Charleston Road Registry',
'foo','Charleston Road Registry',
'food','Internet Naming',
'foodnetwork','Not assigned',
'football','Binky Moon',
'ford','Ford Motor',
'forex','Dog Beach',
'forsale','Dog Beach',
'forum','Fegistry',
'foundation','Public Interest Registry',
'fox','FOX Registry',
'free','Amazon Registry Services',
'fresenius','Fresenius Immobilien-Verwaltungs',
'frl','FRLregistry',
'frogans','OP3FT',
'frontdoor','Not assigned',
'frontier','Frontier Communications',
'ftr','Frontier Communications',
'fujitsu','Fujitsu',
'fujixerox','Not assigned',
'fun','Radix Technologies',
'fund','Binky Moon',
'furniture','Binky Moon',
'futbol','Dog Beach',
'fyi','Binky Moon',
'gal','Asociación puntoGAL',
'gallery','Binky Moon',
'gallo','Gallo Vineyards',
'gallup','Gallup',
'game','XYZ.COM',
'games','Dog Beach',
'gap','The Gap',
'garden','Registry Services',
'gay','Registry Services',
'gbiz','Charleston Road Registry',
'gdn','Joint Stock Company Navigation-information systems',
'gea','GEA Group',
'gent','Easyhost',
'genting','Resorts World',
'george','Wal-Mart Stores',
'ggee','GMO Internet',
'gift','Uniregistry',
'gifts','Binky Moon',
'gives','Public Interest Registry',
'giving','Public Interest Registry',
'glade','Not assigned',
'glass','Binky Moon',
'gle','Charleston Road Registry',
'global','Identity Digital',
'globo','Globo Comunicação e Participações',
'gmail','Charleston Road Registry',
'gmbh','Binky Moon',
'gmo','GMO Internet',
'gmx','1&1 Mail & Media',
'godaddy','Go Daddy East',
'gold','Binky Moon',
'goldpoint','YODOBASHI CAMERA',
'golf','Binky Moon',
'goo','Not assigned',
'goodhands','Not assigned',
'goodyear','The Goodyear Tire & Rubber',
'goog','Charleston Road Registry',
'google','Charleston Road Registry',
'gop','Republican State Leadership Committee',
'got','Amazon Registry Services',
'grainger','Grainger Registry Services',
'graphics','Binky Moon',
'gratis','Binky Moon',
'green','Identity Digital',
'gripe','Binky Moon',
'grocery','Wal-Mart Stores',
'group','Binky Moon',
'guardian','Not assigned',
'gucci','Guccio Gucci',
'guge','Charleston Road Registry',
'guide','Binky Moon',
'guitars','XYZ.COM',
'guru','Binky Moon',
'hair','XYZ.COM',
'hamburg','Hamburg Top-Level-Domain',
'hangout','Charleston Road Registry',
'haus','Dog Beach',
'hbo','HBO Registry Services',
'hdfc','Housing Development Finance Corporation',
'hdfcbank','HDFC Bank',
'health','Registry Services',
'healthcare','Binky Moon',
'help','Innovation Service',
'helsinki','City of Helsinki',
'here','Charleston Road Registry',
'hermes','Hermes International',
'hgtv','Not assigned',
'hiphop','Dot Hip Hop',
'hisamitsu','Hisamitsu Pharmaceutical',
'hitachi','Hitachi',
'hiv','Internet Naming',
'hkt','PCCW-HKT DataCom Services',
'hockey','Binky Moon',
'holdings','Binky Moon',
'holiday','Binky Moon',
'homedepot','Home Depot Product Authority',
'homegoods','The TJX Companies',
'homes','XYZ.COM',
'homesense','The TJX Companies',
'honda','Honda Motor',
'honeywell','Not assigned',
'horse','Registry Services',
'hospital','Binky Moon',
'host','Radix Technologies',
'hosting','XYZ.COM',
'hot','Amazon Registry Services',
'hoteles','Not assigned',
'hotels','Booking.com',
'hotmail','Microsoft Corporation',
'house','Binky Moon',
'how','Charleston Road Registry',
'hsbc','HSBC Global Services',
'htc','Not assigned',
'hughes','Hughes Satellite Systems',
'hyatt','Hyatt GTLD',
'hyundai','Hyundai Motor',
'ibm','IBM',
'icbc','Industrial and Commercial Bank of China',
'ice','IntercontinentalExchange',
'icu','Shortdot SA',
'ieee','IEEE Global',
'ifm','ifm electronic',
'iinet','Not assigned',
'ikano','Ikano',
'imamat','Fondation Aga Khan',
'imdb','Amazon Registry Services',
'immo','Binky Moon',
'immobilien','Dog Beach',
'inc','Intercap Registry',
'industries','Binky Moon',
'infiniti','Nissan Motor',
'ing','Charleston Road Registry',
'ink','Registry Services',
'institute','Binky Moon',
'insurance','fTLD Registry Services',
'insure','Binky Moon',
'intel','Not assigned',
'international','Binky Moon',
'intuit','Intuit Administrative Services',
'investments','Binky Moon',
'ipiranga','Ipiranga Produtos de Petroleo',
'irish','Binky Moon',
'iselect','Not assigned',
'ismaili','Fondation Aga Khan',
'ist','Istanbul Metropolitan Municipality',
'istanbul','Istanbul Metropolitan Municipality',
'itau','Itau Unibanco Holding',
'itv','ITV Services',
'iveco','Not assigned',
'iwc','Not assigned',
'jaguar','Jaguar Land Rover',
'java','Oracle',
'jcb','JCB',
'jcp','Not assigned',
'jeep','FCA US',
'jetzt','Binky Moon',
'jewelry','Binky Moon',
'jio','Reliance Industries',
'jlc','Not assigned',
'jll','Jones Lang LaSalle',
'jmp','Matrix IP',
'jnj','Johnson & Johnson',
'jobs','Employ Media',
'joburg','ZA Central Registry',
'jot','Amazon Registry Services',
'joy','Amazon Registry Services',
'jpmorgan','JPMorgan Chase',
'jprs','Japan Registry Services',
'juegos','Dog Beach',
'juniper','Juniper Networks',
'kaufen','Dog Beach',
'kddi','KDDI',
'kerryhotels','Kerry Trading',
'kerrylogistics','Not assigned',
'kerryproperties','Kerry Trading',
'kfh','Kuwait Finance House',
'kia','Kia Motors',
'kids','DotKids Foundation',
'kim','Identity Digital',
'kinder','Not assigned',
'kindle','Amazon Registry Services',
'kitchen','Binky Moon',
'kiwi','DOT KIWI',
'koeln','dotKoeln',
'komatsu','Komatsu',
'kosher','Kosher Marketing Assets',
'kpmg','KPMG International',
'kpn','Koninklijke KPN',
'krd','KRG Department of Information Technology',
'kred','KredTLD',
'kuokgroup','Kerry Trading',
'kyoto','Kyoto Jyoho Gakuen',
'lacaixa','Fundación Bancaria Caixa d\'Estalvis',
'ladbrokes','Not assigned',
'lamborghini','Automobili Lamborghini',
'lamer','The Estée Lauder Companies',
'lancaster','Not assigned',
'lancia','Not assigned',
'lancome','Not assigned',
'land','Binky Moon',
'landrover','Jaguar Land Rover',
'lanxess','LANXESS',
'lasalle','Jones Lang LaSalle',
'lat','XYZ.COM',
'latino','Dish DBS',
'latrobe','La Trobe University',
'law','Registry Services',
'lawyer','Dog Beach',
'lds','IRI Domain Management',
'lease','Binky Moon',
'leclerc','A.C.D. LEC',
'lefrak','LeFrak Organization',
'legal','Binky Moon',
'lego','LEGO Juris',
'lexus','Toyota Motor',
'lgbt','Identity Digital',
'liaison','Not assigned',
'lidl','Schwarz Domains und Services',
'life','Binky Moon',
'lifeinsurance','American Council of Life Insurers',
'lifestyle','Internet Naming',
'lighting','Binky Moon',
'like','Amazon Registry Services',
'lilly','Eli Lilly',
'limited','Binky Moon',
'limo','Binky Moon',
'lincoln','Ford Motor',
'linde','Not assigned',
'link','Nova Registry',
'lipsy','Not assigned',
'live','Dog Beach',
'living','Internet Naming',
'lixil','Not assigned',
'llc','Identity Digital',
'llp','Intercap Registry',
'loan','dot Loan',
'loans','Binky Moon',
'locker','Orange Domains',
'locus','Locus Analytics',
'loft','Not assigned',
'lol','XYZ.COM',
'london','Dot London Domains',
'lotte','Lotte Holdings',
'lotto','Identity Digital',
'love','Waterford',
'lpl','LPL Holdings',
'lplfinancial','LPL Holdings',
'ltd','Binky Moon',
'ltda','InterNetX',
'lundbeck','H. Lundbeck',
'lupin','Not assigned',
'luxe','Registry Services',
'luxury','Luxury Partners',
'macys','Not assigned',
'madrid','Comunidad de Madrid',
'maif','Mutuelle Assurance Instituteur France',
'maison','Binky Moon',
'makeup','XYZ.COM',
'man','MAN Truck & Bus',
'management','Binky Moon',
'mango','PUNTO FA',
'map','Charleston Road Registry',
'market','Dog Beach',
'marketing','Binky Moon',
'markets','Dog Beach',
'marriott','Marriott Worldwide',
'marshalls','The TJX Companies',
'maserati','Not assigned',
'mattel','Mattel IT Services',
'mba','Binky Moon',
'mcd','Not assigned',
'mcdonalds','Not assigned',
'mckinsey','McKinsey Holdings',
'med','Medistry',
'media','Binky Moon',
'meet','Charleston Road Registry',
'melbourne','State of Victoria',
'meme','Charleston Road Registry',
'memorial','Dog Beach',
'men','Exclusive Registry',
'menu','Dot Menu Registry',
'meo','Not assigned',
'merck','Merck Registry Holdings',
'merckmsd','MSD Registry Holdings',
'metlife','Not assigned',
'miami','Registry Services',
'microsoft','Microsoft Corporation',
'mini','Bayerische Motoren Werke',
'mint','Intuit Administrative Services',
'mit','Massachusetts Institute of Technology',
'mitsubishi','Mitsubishi Corporation',
'mlb','MLB Advanced Media',
'mls','The Canadian Real Estate Association',
'mma','MMA IARD',
'mobile','Dish DBS',
'mobily','Not assigned',
'moda','Dog Beach',
'moe','Interlink Systems Innovation',
'moi','Amazon Registry Services',
'mom','XYZ.COM',
'monash','Monash University',
'money','Binky Moon',
'monster','XYZ.COM',
'montblanc','Not assigned',
'mopar','Not assigned',
'mormon','IRI Domain Management',
'mortgage','Dog Beach',
'moscow','FAITID',
'moto','Motorola Trademark Holdings',
'motorcycles','XYZ.COM',
'mov','Charleston Road Registry',
'movie','Binky Moon',
'movistar','Not assigned',
'msd','MSD Registry Holdings',
'mtn','MTN Dubai',
'mtpc','Not assigned',
'mtr','MTR Corporation',
'music','DotMusic',
'mutual','Not assigned',
'mutuelle','Not assigned',
'nab','National Australia Bank',
'nadex','Not assigned',
'nagoya','GMO Registry',
'nationwide','Not assigned',
'natura','Not assigned',
'navy','Dog Beach',
'nba','NBA REGISTRY',
'nec','NEC Corporation',
'netbank','Commonwealth Bank of Australia',
'netflix','Netflix',
'network','Binky Moon',
'neustar','NeuStar',
'new','Charleston Road Registry',
'newholland','Not assigned',
'news','Dog Beach',
'next','Next plc',
'nextdirect','Next plc',
'nexus','Charleston Road Registry',
'nfl','NFL Reg Ops',
'ngo','Public Interest Registry',
'nhk','Japan Broadcasting Corporation',
'nico','DWANGO',
'nike','NIKE',
'nikon','NIKON CORPORATION',
'ninja','Dog Beach',
'nissan','Nissan Motor',
'nissay','Nippon Life Insurance',
'nokia','Nokia Corporation',
'northwesternmutual','Not assigned',
'norton','Gen Digital',
'now','Amazon Registry Services',
'nowruz','Emergency Back-End Registry Operator',
'nowtv','Starbucks (HK)',
'nra','National Rifle Association',
'nrw','Minds + Machines',
'ntt','Nippon Telegraph and Telephone',
'nyc','The City of New York',
'obi','OBI Group',
'observer','Fegistry',
'off','Not assigned',
'office','Microsoft Corporation',
'okinawa','BRregistry',
'olayan','Competrol (Luxembourg)',
'olayangroup','Competrol (Luxembourg)',
'oldnavy','Not assigned',
'ollo','Dish DBS',
'omega','The Swatch Group',
'one','One.com',
'ong','Public Interest Registry',
'onl','Jolly Host',
'online','Radix Technologies',
'onyourside','Not assigned',
'ooo','INFIBEAM AVENUES',
'open','American Express',
'oracle','Oracle Corporation',
'orange','Orange Brand Services',
'organic','Identity Digital',
'orientexpress','Not assigned',
'origins','The Estée Lauder Companies',
'osaka','Osaka Registry',
'otsuka','Otsuka Holdings',
'ott','Dish DBS',
'ovh','OVH SAS',
'page','Charleston Road Registry',
'pamperedchef','Not assigned',
'panasonic','Panasonic Corporation',
'panerai','Not assigned',
'paris','City of Paris',
'pars','Emergency Back-End Registry Operator',
'partners','Binky Moon',
'parts','Binky Moon',
'party','Blue Sky Registry',
'passagens','Not assigned',
'pay','Amazon Registry Services',
'pccw','PCCW Enterprises',
'pet','Identity Digital',
'pfizer','Pfizer',
'pharmacy','National Association of Boards of Pharmacy',
'phd','Charleston Road Registry',
'philips','Koninklijke Philips',
'phone','Dish DBS',
'photo','Registry Services',
'photography','Binky Moon',
'photos','Binky Moon',
'physio','PhysBiz',
'piaget','Not assigned',
'pics','XYZ.COM',
'pictet','Banque Pictet',
'pictures','Binky Moon',
'pid','Top Level Spectrum',
'pin','Amazon Registry Services',
'ping','Ping Registry Provider',
'pink','Identity Digital',
'pioneer','Pioneer Corporation',
'pizza','Binky Moon',
'place','Binky Moon',
'play','Charleston Road Registry',
'playstation','Sony Computer Entertainment',
'plumbing','Binky Moon',
'plus','Binky Moon',
'pnc','PNC Domain',
'pohl','Deutsche Vermögensberatung',
'poker','Identity Digital',
'politie','Politie Nederland',
'porn','ICM Registry PN',
'post','Universal Postal Union',
'pramerica','Not assigned',
'praxi','Praxi',
'press','Radix Technologies',
'prime','Amazon Registry Services',
'prod','Charleston Road Registry',
'productions','Binky Moon',
'prof','Charleston Road Registry',
'progressive','Progressive Casualty Insurance',
'promo','Identity Digital',
'properties','Binky Moon',
'property','Digital Property Infrastructure',
'protection','XYZ.COM',
'pru','Prudential Financial',
'prudential','Prudential Financial',
'pub','Dog Beach',
'pwc','PricewaterhouseCoopers',
'qpon','DOTQPON',
'quebec','PointQuébec',
'quest','XYZ.COM',
'qvc','Not assigned',
'racing','Premier Registry',
'radio','Digity',
'raid','Not assigned',
'read','Amazon Registry Services',
'realestate','dotRealEstate',
'realtor','Real Estate Domains',
'realty','Internet Naming',
'recipes','Binky Moon',
'red','Identity Digital',
'redstone','Not assigned',
'redumbrella','Travelers TLD',
'rehab','Dog Beach',
'reise','Binky Moon',
'reisen','Binky Moon',
'reit','National Association of Real Estate Investment Trusts',
'reliance','Reliance Industries',
'ren','ZDNS International',
'rent','XYZ.COM',
'rentals','Binky Moon',
'repair','Binky Moon',
'report','Binky Moon',
'republican','Dog Beach',
'rest','Punto 2012',
'restaurant','Binky Moon',
'review','dot Review',
'reviews','Dog Beach',
'rexroth','Robert Bosch',
'rich','iRegistry',
'richardli','Pacific Century Asset Management',
'ricoh','Ricoh Company',
'rightathome','Not assigned',
'ril','Reliance Industries',
'rio','Empresa Municipal de Informática',
'rip','Dog Beach',
'rmit','Not assigned',
'rocher','Not assigned',
'rocks','Dog Beach',
'rodeo','Registry Services',
'rogers','Rogers Communications',
'room','Amazon Registry Services',
'rsvp','Charleston Road Registry',
'rugby','World Rugby Strategic Developments',
'ruhr','dotSaarland',
'run','Binky Moon',
'rwe','RWE',
'ryukyu','BRregistry',
'saarland','dotSaarland',
'safe','Amazon Registry Services',
'safety','Safety Registry Services',
'sakura','SAKURA internet',
'sale','Dog Beach',
'salon','Binky Moon',
'samsclub','Wal-Mart Stores',
'samsung','SAMSUNG SDS',
'sandvik','Sandvik AB',
'sandvikcoromant','Sandvik AB',
'sanofi','Sanofi',
'sap','SAP',
'sapo','Not assigned',
'sarl','Binky Moon',
'sas','Research IP',
'save','Amazon Registry Services',
'saxo','Saxo Bank',
'sbi','State Bank of India',
'sbs','Shortdot SA',
'sca','Not assigned',
'scb','The Siam Commercial Bank',
'schaeffler','Schaeffler Technologies',
'schmidt','SCHMIDT GROUPE',
'scholarships','Scholarships.com',
'school','Binky Moon',
'schule','Binky Moon',
'schwarz','Schwarz Domains und Services',
'science','dot Science',
'scjohnson','Not assigned',
'scor','Not assigned',
'scot','Dot Scot Registry',
'search','Charleston Road Registry',
'seat','SEAT',
'secure','Amazon Registry Services',
'security','XYZ.COM',
'seek','Seek Limited',
'select','Registry Services',
'sener','Sener Ingeniería y Sistemas',
'services','Binky Moon',
'ses','Not assigned',
'seven','Seven West Media',
'sew','SEW-EURODRIVE',
'sex','ICM Registry SX',
'sexy','Internet Naming',
'sfr','Societe Francaise du Radiotelephone',
'shangrila','Shangri-La International Hotel Management',
'sharp','Sharp Corporation',
'shaw','Not assigned',
'shell','Shell Information Technology International',
'shia','Emergency Back-End Registry Operator',
'shiksha','Identity Digital',
'shoes','Binky Moon',
'shop','GMO Registry',
'shopping','Binky Moon',
'shouji','Beijing Qihu Keji',
'show','Binky Moon',
'showtime','Not assigned',
'shriram','Not assigned',
'silk','Amazon Registry Services',
'sina','Sina Corporation',
'singles','Binky Moon',
'site','Radix Technologies',
'ski','Identity Digital',
'skin','XYZ.COM',
'sky','Sky UK',
'skype','Microsoft Corporation',
'sling','DISH Technologies',
'smart','Smart Communications',
'smile','Amazon Registry Services',
'sncf','Société Nationale SNCF',
'soccer','Binky Moon',
'social','Dog Beach',
'softbank','SoftBank Group',
'software','Dog Beach',
'sohu','Sohu.com',
'solar','Binky Moon',
'solutions','Binky Moon',
'song','Amazon Registry Services',
'sony','Sony Corporation',
'soy','Charleston Road Registry',
'spa','Asia Spa and Wellness Promotion Council',
'space','Radix Technologies',
'spiegel','Not assigned',
'sport','SportAccord',
'spot','Amazon Registry Services',
'spreadbetting','Not assigned',
'srl','InterNetX',
'srt','Not assigned',
'stada','STADA Arzneimittel',
'staples','Staples',
'star','Star India',
'starhub','Not assigned',
'statebank','State Bank of India',
'statefarm','State Farm Mutual Automobile Insurance',
'statoil','Not assigned',
'stc','Saudi Telecom Company',
'stcgroup','Saudi Telecom Company',
'stockholm','Stockholms kommun',
'storage','XYZ.COM',
'store','Radix Technologies',
'stream','dot Stream',
'studio','Dog Beach',
'study','Registry Services',
'style','Binky Moon',
'sucks','Vox Populi Registry',
'supplies','Binky Moon',
'supply','Binky Moon',
'support','Binky Moon',
'surf','Registry Services',
'surgery','Binky Moon',
'suzuki','Suzuki Motor',
'swatch','The Swatch Group',
'swiftcover','Not assigned',
'swiss','Swiss Confederation',
'sydney','State of New South Wales',
'symantec','Not assigned',
'systems','Binky Moon',
'tab','Tabcorp Holdings',
'taipei','Taipei City Government',
'talk','Amazon Registry Services',
'taobao','Alibaba Group',
'target','Target Domain Holdings',
'tatamotors','Tata Motors',
'tatar','Coordination Center of Regional Domain of Tatarstan Republic',
'tattoo','Registry Services',
'tax','Binky Moon',
'taxi','Binky Moon',
'tci','Emergency Back-End Registry Operator',
'tdk','TDK Corporation',
'team','Binky Moon',
'tech','Radix Technologies',
'technology','Binky Moon',
'telecity','Not assigned',
'telefonica','Not assigned',
'temasek','Temasek Holdings',
'tennis','Binky Moon',
'teva','Teva Pharmaceutical Industries',
'theater','Binky Moon',
'theatre','XYZ.COM',
'tiaa','Teachers Insurance and Annuity Association',
'tickets','XYZ.COM',
'tienda','Binky Moon',
'tiffany','Not assigned',
'tips','Binky Moon',
'tires','Binky Moon',
'tirol','punkt Tirol',
'tjmaxx','The TJX Companies',
'tjx','The TJX Companies',
'tkmaxx','The TJX Companies',
'tmall','Alibaba Group',
'today','Binky Moon',
'tokyo','GMO Registry',
'tools','Binky Moon',
'top','Hong Kong Zhongze International',
'toray','Toray Industries',
'toshiba','Toshiba Corporation',
'total','TotalEnergies',
'tours','Binky Moon',
'town','Binky Moon',
'toyota','Toyota Motor',
'toys','Binky Moon',
'trade','Elite Registry',
'trading','Dog Beach',
'training','Binky Moon',
'travelchannel','Not assigned',
'travelers','Travelers TLD',
'travelersinsurance','Travelers TLD',
'trust','Internet Naming',
'trv','Travelers TLD',
'tube','Latin American Telecom',
'tui','TUI',
'tunes','Amazon Registry Services',
'tushu','Amazon Registry Services',
'tvs','T V Sundram Iyengar & Sons',
'ubank','National Australia Bank',
'ubs','UBS',
'uconnect','Not assigned',
'unicom','China United Network Communications',
'university','Binky Moon',
'uno','Radix Technologies',
'uol','UBN INTERNET',
'ups','UPS Market Driver',
'vacations','Binky Moon',
'vana','D3 Registry',
'vanguard','The Vanguard Group',
'vegas','Dot Vegas',
'ventures','Binky Moon',
'verisign','VeriSign',
'versicherung','tldbox',
'vet','Dog Beach',
'viajes','Binky Moon',
'video','Dog Beach',
'vig','Vienna Insurance Group',
'viking','Viking River Cruises',
'villas','Binky Moon',
'vin','Binky Moon',
'vip','Registry Services',
'virgin','Virgin Enterprises',
'visa','Visa Worldwide',
'vision','Binky Moon',
'vista','Not assigned',
'vistaprint','Not assigned',
'viva','Saudi Telecom Company',
'vivo','Telefonica Brasil',
'vlaanderen','DNS.be',
'vodka','Registry Services',
'volkswagen','Not assigned',
'volvo','Volvo Holding Sverige',
'vote','Monolith Registry',
'voting','Valuetainment',
'voto','Monolith Registry',
'voyage','Binky Moon',
'vuelos','Not assigned',
'wales','Nominet UK',
'walmart','Wal-Mart Stores',
'walter','Sandvik AB',
'wang','Zodiac Wang',
'wanggou','Amazon Registry Services',
'warman','Not assigned',
'watch','Binky Moon',
'watches','Identity Digital',
'weather','The Weather Company',
'weatherchannel','The Weather Company',
'webcam','dot Webcam',
'weber','Saint-Gobain Weber',
'website','Radix Technologies',
'wed','Emergency Back-End Registry Operator',
'wedding','Registry Services',
'weibo','Sina Corporation',
'weir','Weir Group IP',
'whoswho','Who\'s Who Registry',
'wien','punkt.wien',
'wiki','Registry Services',
'williamhill','William Hill Organization',
'win','First Registry',
'windows','Microsoft Corporation',
'wine','Binky Moon',
'winners','The TJX Companies',
'wme','William Morris Endeavor',
'wolterskluwer','Not assigned',
'woodside','Woodside Petroleum',
'work','Registry Services',
'works','Binky Moon',
'world','Binky Moon',
'wow','Amazon Registry Services',
'wtc','World Trade Centers Association',
'wtf','Binky Moon',
'xbox','Microsoft Corporation',
'xerox','Xerox DNHC',
'xfinity','Not assigned',
'xihuan','Beijing Qihu Keji',
'xin','Elegant Leader',
'xperia','Not assigned',
'xyz','XYZ.COM',
'yachts','XYZ.COM',
'yahoo','Yahoo',
'yamaxun','Amazon Registry Services',
'yandex','YANDEX',
'yodobashi','YODOBASHI CAMERA',
'yoga','Registry Services',
'yokohama','GMO Registry',
'you','Amazon Registry Services',
'youtube','Charleston Road Registry',
'yun','Beijing Qihu Keji',
'zappos','Amazon Registry Services',
'zara','Industria de Diseño Textil',
'zero','Amazon Registry Services',
'zip','Charleston Road Registry',
'zippo','Not assigned',
'zone','Binky Moon',
'zuerich','Kanton Zürich',

# Internationalized Domain Names (IDN) ccTLDs
'xn--3e0b707e','한국 (Korea)',
'xn--45brj9c','ভারত (India)',
'xn--54b7fta0cc','বাংলা (Bangladesh)',
'xn--80adxhks','москва (Moscow)',
'xn--80ao21a','қаз (Kazakhstan)',
'xn--90a3ac','срб (Serbia)',
'xn--90ae','бг (Bulgaria)',
'xn--90ais','бел (Belarus)',
'xn--clchc0ea0b2g2a9gcd','சிங்கப்பூர் (Singapore)',
'xn--d1alf','мкд (North Macedonia)',
'xn--e1a4c','ею (EU)',
'xn--fiqs8s','中国 (China)',
'xn--fiqz9s','中國 (China)',
'xn--fpcrj9c3d','భారత్ (India)',
'xn--fzc2c9e2c','ලංකා (Sri Lanka)',
'xn--gecrj9c','ભારત (India)',
'xn--h2brj9c','भारत (India)',
'xn--j1amh','укр (Ukraine)',
'xn--j6w193g','香港 (Hong Kong)',
'xn--kprw13d','台湾 (Taiwan)',
'xn--kpry57d','台灣 (Taiwan)',
'xn--l1acc','мон (Mongolia)',
'xn--lgbbat1ad8j','الجزائر (Algeria)',
'xn--mgb9awbf','عمان (Oman)',
'xn--mgba3a4f16a','ایران (Iran)',
'xn--mgbaam7a8h','امارات (UAE)',
'xn--mgbab2bd','بازار (Bazaar)',
'xn--mgbah1a3hjkrd','موريتانيا (Mauritania)',
'xn--mgbai9azgqp6j','پاکستان (Pakistan)',
'xn--mgbayh7gpa','الاردن (Jordan)',
'xn--mgbbh1a','بارت (India)',
'xn--mgbbh1a71e','بھارت (India)',
'xn--mgbc0a9azcg','المغرب (Morocco)',
'xn--mgbca7dzdo','ابوظبي (Abu Dhabi)',
'xn--mgbcpq6gpa1a','البحرين (Bahrain)',
'xn--mgberp4a5d4ar','السعودية (Saudi Arabia)',
'xn--mgbgu82a','ڀارت (India)',
'xn--mgbpl2fh','سودان (Sudan)',
'xn--mgbtx2b','عراق (Iraq)',
'xn--mgbx4cd0ab','مليسيا (Malaysia)',
'xn--mix891f','澳門 (Macau)',
'xn--ngbc5azd','شبكة (Network)',
'xn--ngbe9e0a','بيتك (Kuwait Finance House)',
'xn--ngbrx','عرب (Arab)',
'xn--node','გე (Georgia)',
'xn--o3cw4h','ไทย (Thailand)',
'xn--ogbpf8fl','سورية (Syria)',
'xn--p1acf','рус (Russian)',
'xn--p1ai','рф (Russia)',
'xn--pgbs0dh','تونس (Tunisia)',
'xn--q7ce6a','ລາວ (Laos)',
'xn--qxa6a','ευ (EU)',
'xn--qxam','ελ (Greece)',
'xn--rvc1e0am3e','ഭാരതം (India)',
'xn--s9brj9c','ਭਾਰਤ (India)',
'xn--wgbh1c','مصر (Egypt)',
'xn--wgbl6a','قطر (Qatar)',
'xn--xkc2al3hye2a','இலங்கை (Sri Lanka)',
'xn--xkc2dl3a5ee0h','இந்தியா (India)',
'xn--y9a3aq','հայ (Armenia)',
'xn--yfro4i67o','新加坡 (Singapore)',
'xn--ygbi2ammx','فلسطين (Palestine)',
);

1;